### ISSUE TITLE
market should disallow 0.0000 EOS sales

### ISSUE THREAD

**Issue by GassaFM** [LetItPlay/CryptoWizards-SmartContract#1]
https://github.com/LetItPlay/CryptoWizards-SmartContract/blob/777cca21c0475ec7729c90821b99ce7aeb3a8f6d/marketplace/marketplace.cpp#L48

That `>=` should be `>` instead.

When trying to buy, a deal created for 0.0000 EOS fails with the following message:

~~~~~
Error Buying Wizard

Error details:
eosio_assert_message_exception
eosio_assert_message assertion failure
assertion failure with message: must transfer positive quantity
~~~~~

So it would be better to disallow to create such deals in the first place.

**Comment by opcheese** [comment]
I actually think that we should check for > 0.0001 EOS. То deal with a number of nasty problems
