### ISSUE TITLE
shop items generation: array index out of bounds

### ISSUE THREAD

**Issue by GassaFM** [LetItPlay/CryptoWizards-SmartContract#2]
https://github.com/LetItPlay/CryptoWizards-SmartContract/blob/928e6116ad1a66380e5fa4897d19514ee44948d8/wizContract.cpp#L126

This is a bug.
`shopArray[itemType]` should in fact be `shopArray[i]`.
The item type can be 0..9, but shopArray is currently of length 2.

How does this not crash, at least sometimes?

**Comment by opcheese** [comment]
It's a new change. We'll look into it.

I believe it meant to be shopArray[i]
