### ISSUE TITLE
random number generation: bug in improbable case

### ISSUE THREAD

**Issue by GassaFM** [LetItPlay/CryptoWizards-SmartContract#3]
https://github.com/LetItPlay/CryptoWizards-SmartContract/blob/928e6116ad1a66380e5fa4897d19514ee44948d8/wizContract.cpp#L188

This is a bug in handling the improbable case (still a bit probable for very small lengths though).
The line declares a new variable instead of assigning to the existing one.

Note that some compiler options (like `-Wshadow` shadowing warnings for GCC) may prevent such bugs.

**Comment by GassaFM** [comment]
For what it's worth, this **does** happen for calls with `length = 1`.

**Comment by opcheese** [comment]
Thank you! I have no idea how I missed that.
