### ISSUE TITLE
outdated contract published?

### ISSUE THREAD

**Issue by GassaFM** [LetItPlay/CryptoWizards-SmartContract#5]
https://github.com/LetItPlay/CryptoWizards-SmartContract/blob/84e9a06e0dda446c6acea786df0bd219e1afdecc/pvp/pvp.cpp#L576

This does not seem to be the latest version of the contract.
In the published version, the default value for the `powerCoef` of `runFightRoundGenotype` is commented out, so this call would not compile.

**Comment by qpIlIpp** [comment]
Look carefully, it's not commented. Just default value is shown to make the code more readable.
`int powerCoef/* = 1*/`
pvp.hpp file contains `, int powerCoef = 1`
https://github.com/LetItPlay/CryptoWizards-SmartContract/blob/84e9a06e0dda446c6acea786df0bd219e1afdecc/pvp/pvp.hpp#L147

**Comment by GassaFM** [comment]
Ow, sorry, my bad!
Gotta learn more C++ :) .

**Comment by qpIlIpp** [comment]
no problem =)
